version: '3.8'
services:
  ocserv:
    image: coralhl/ocserv
    restart: unless-stopped
    container_name: ocserv
    hostname: www.example.com
    ports:
      - 443:443/udp
      - 443:443
    volumes:
      - "/opt/docker/ocserv:/etc/ocserv"
    sysctls:
      - net.ipv4.ip_forward=1
    cap_add:
      - NET_ADMIN
    security_opt:
      - no-new-privileges
